/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./src/components/BaseCheckbox.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseTextBox: typeof import('./src/components/BaseTextBox.vue')['default']
    ButtonLink: typeof import('./src/components/ButtonLink.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NProgress: typeof import('naive-ui')['NProgress']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NTextarea: typeof import('naive-ui')['NTextarea']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Playback: typeof import('./src/components/Playback.vue')['default']
    RecordingControl: typeof import('./src/components/RecordingControl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchulteResults: typeof import('./src/components/SchulteResults.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
    WordCard: typeof import('./src/components/WordCard.vue')['default']
    WordCounter: typeof import('./src/components/WordCounter.vue')['default']
  }
}
