FROM node:17-alpine as build-stage

RUN mkdir -p /opt/app
WORKDIR /opt/app

ENV PATH /opt/app/node_modules/.bin:$PATH

COPY package*.json /opt/app/

RUN npm install

COPY . /opt/app

RUN npm run build

FROM nginx

COPY --from=build-stage /opt/app/dist /usr/share/nginx/html

RUN chgrp -R root /var/cache/nginx /var/run /var/log/nginx && \
    chmod -R 770 /var/cache/nginx /var/run /var/log/nginx

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
