variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME
    GIT_STRATEGY: 'fetch'
    GIT_CHECKOUT: 'true'
    GIT_CLEAN_FLAGS: 'none'
    GIT_DEPTH: 0

stages:
    - build
    - test

build-image:
    image: docker:cli
    stage: build
    before-script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.andyi95.com
    script:
        - app/stage/build
    only:
        - dev

test-image:
    stage: test
    script:
        - app/stage/test
    depends-on:
        -