variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME
    GIT_STRATEGY: 'pull'
    GIT_CHECKOUT: 'true'
    GIT_CLEAN_FLAGS: 'none'
    GIT_DEPTH: 0

stages:
    - build
    - test
    - deploy

.docker_build: &docker-build
    stage: build
    tags:
        - docker
    before_script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.andyi95.com
        - |
            if [ -n "$(git tag --points-at HEAD)" ]; then
              export APP_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
            else
              export APP_VERSION=$(git rev-parse --short HEAD)
            fi
            export COMPOSE_FILE=docker-compose.yaml:docker-compose.stage.yaml

build:frontend:
    <<: *docker-build
    script:
        - TAG=${CI_COMMIT_REF_SLUG} docker compose build frontend
        - TAG=${CI_COMMIT_REF_SLUG} docker compose push frontend
    only:
        changes:
            - frontend/**/*
            - app/**/*
            - .gitlab-ci.yml

build:backend:
    <<: *docker-build
    script:
        - TAG=${CI_COMMIT_REF_SLUG} docker compose build backend
        - TAG=${CI_COMMIT_REF_SLUG} docker compose push backend
    only:
        changes:
            - app/**/*
            - backend/**/*
            - .gitlab-ci.yml

test:frotend:
    stage: test
    tags:
        - docker
    script:
        - TAG=${CI_COMMIT_REF_SLUG} docker compose pull frontend
        - TAG=${CI_COMMIT_REF_SLUG} docker compose up -d frontend
        - docker compose ps
        - sleep 10
        - docker compose down

test:backend:
    stage: test
    tags:
        - docker
    script:
        - TAG=${CI_COMMIT_REF_SLUG} docker compose pull backend
        - TAG=${CI_COMMIT_REF_SLUG} docker compose up -d backend
        - docker compose ps
        - sleep 10
        - docker compose down

.deploy_script: &deploy_script
    variables:
        GIT_STRATEGY: 'none'
        GIT_CHECKOUT: 'false'
        GIT_CLEAN_FLAGS: 'none'
        GIT_DEPTH: 0
    script:
        - app/stage/deploy $DEPLOY_COMPONENT
    stage: deploy
    when: manual
    tags:
        - ssh
        - dev

deploy:development:frontend:
    <<: *deploy_script
    variables:
        DEPLOY_COMPONENT: frontend
    needs:
        - test:frontend
    environment:
        name: development
        deployment_tier: development
        url: https://reader.dev.andyi95.com/

deploy:development:backend:
    <<: *deploy_script
    variables:
        DEPLOY_COMPONENT: backend
    needs:
        - test:backend
    environment:
        name: development
        deployment_tier: development
        url: https://reader.dev.andyi95.com/

deploy:production:backend:
    <<: *deploy_script
    variables:
        DEPLOY_COMPONENT: backend
    needs:
        - test:backend
    environment:
        name: production
        deployment_tier: production
        url: https://text-tools.ru/

deploy:production:frontend:
    <<: *deploy_script
    variables:
        DEPLOY_COMPONENT: frontend
    needs:
        - test:frontend
    environment:
        name: production
        deployment_tier: production
        url: https://text-tools.ru/

