

stages:
    - build
    - test
    - deploy:development
    - deploy:production

variables:
    DEPLOY_ENVIRONMENT:
        value: "development"
        options:
            - "development"
            - "production"
            - "home"
        description: "Environment for deploy"

workflow:
    rules:
        - if: '$DEPLOY_ENVIRONMENT == "development"'
          variables:

.docker_build: &docker-build
    variables:
        GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME
        GIT_STRATEGY: 'pull'
        GIT_CHECKOUT: 'true'
        GIT_CLEAN_FLAGS: 'none'
        GIT_DEPTH: 0
    stage: build
    tags:
        - docker
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - |
            if [ -n "$(git tag --points-at HEAD)" ]; then
              export APP_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
            else
              export APP_VERSION=$(git rev-parse --short HEAD)
            fi
            export COMPOSE_FILE=docker-compose.yaml:docker-compose.stage.yaml
        - app/stage/vars $CI_COMMIT_REF_SLUG
    only:
        refs:
            - dev
            - development
            - master

build:frontend:
    <<: *docker-build
    script:
        - TAG=${CI_COMMIT_SHORT_SHA} docker compose build frontend
        - TAG=${CI_COMMIT_SHORT_SHA} docker compose push frontend

build:backend:
    <<: *docker-build
    script:
        - echo $GAPP_CREDENTIALS_BASE64 | base64 -d > backend/gcloud-service-key.json
        - export GOOGLE_APPLICATION_CREDENTIALS=/app/gcloud-service-key.json
        - TAG=${CI_COMMIT_SHORT_SHA} docker compose build backend
        - TAG=${CI_COMMIT_SHORT_SHA} docker compose push backend

test:frontend:
    stage: test
    tags:
        - docker
    script:
        - app/stage/test frontend
    after_script:
        - docker compose down

test:backend:
    stage: test
    tags:
        - docker
    script:
        - app/stage/test backend
    after_script:
        - docker compose down

.deploy_script: &deploy_script
    variables:
        GIT_STRATEGY: 'none'
        GIT_CHECKOUT: 'false'
        GIT_DEPTH: 0
        GIT_CLONE_PATH: 'none'
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script: >
        app/stage/vars $CI_COMMIT_REF_SLUG &&
        app/stage/deploy $DEPLOY_COMPONENT 
    when: manual
    tags:
        - ssh
        - dev

deploy:development:
    <<: *deploy_script
    stage: deploy:development
#    needs:
#        - test:frontend
    environment:
        name: development
        deployment_tier: development
        url: https://reader.dev.andyi95.com/


deploy:production:backend:
    <<: *deploy_script
    stage: deploy:production
    variables:
        DEPLOY_COMPONENT: backend
    needs:
        - test:backend
    environment:
        name: production
        deployment_tier: production
        url: https://text-tools.ru/

deploy:production:frontend:
    <<: *deploy_script
    stage: deploy:production
    variables:
        DEPLOY_COMPONENT: frontend
    needs:
        - test:frontend
    environment:
        name: production
        deployment_tier: production
        url: https://text-tools.ru/

