version: '3.4'

services:
    frontend:
        image: registry.se.andyi95.com/text-tools/reading-frontend
        build:
            context: frontend
            dockerfile: stage.Dockerfile
        env_file:
            - .env

    backend:
        image: registry.se.andyi95.com/text-tools/reading-backend
        build: backend
        working_dir: /app
        env_file:
            - .env
        depends_on:
            -  redis

    nginx:
        image: nginx:1.19.3
        volumes:
            - ./app/nginx.conf:/etc/nginx/templates/default.conf.template
        restart: unless-stopped
        depends_on:
            - backend
            - frontend
        env_file:
            - .env

    redis:
        image: redis:6.2-alpine
        volumes:
            -   redis-data:/data
        restart: unless-stopped
        command: redis-server --maxmemory 134217728 --maxmemory-policy allkeys-lru

volumes:
    redis-data:

