version: '3.4'

services:
    frontend:
        image: registry.launch.andyi95.com/text-tools/reading-frontend
        build:
            context: frontend
            dockerfile: stage.Dockerfile
        env_file:
            - .env

    backend:
        image: registry.launch.andyi95.com/text-tools/reading-backend
        build: backend
        working_dir: /app
        env_file:
            - .env

    nginx:
        image: nginx:1.19.3
        volumes:
            - ./app/nginx.conf:/etc/nginx/templates/default.conf.template
        restart: unless-stopped
        depends_on:
            - backend
            - frontend
        env_file:
            - .env
