version: '3.4'
services:
    frontend:
        restart: unless-stopped

    backend:
        restart: unless-stopped

    nginx:
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.reader.rule=Host(`reader.stage.andyi95.com`, `text-tools.ru`)"
            - "traefik.http.services.reader.loadbalancer.server.port=80"
            - "traefik.http.middlewares.reader.headers.customrequestheaders.X-Forwarded-Proto=https,wss"

