version: '3.4'
services:
    frontend:
        image: ${CI_REGISTRY_IMAGE}/frontend:${TAG:-latest}
        build:
            context: frontend
            dockerfile: stage.Dockerfile
        restart: unless-stopped

    backend:
        image: ${CI_REGISTRY_IMAGE}/backend:${TAG:-latest}
        restart: unless-stopped

    nginx:
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(${DEPLOYMENT_HOST:-`reader.home.andyi95.com`})"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
            - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}.headers.customrequestheaders.X-Forwarded-Proto=https,wss"
            - traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://www.text-tools.ru/(.*)
            - traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://text-tools.ru/$${1}
            - traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true
