version: '3.4'

services:
    frontend:
        image: andyi95/reading-frontend
        volumes:
            - ./frontend:/app:cached
        env_file:
            - .env

    backend:
        image: andyi95/reading-backend
        volumes:
            - ./backend:/app:cached
        working_dir: /app
        env_file:
            - .env

    nginx:
        image: nginx:1.19.3
        volumes:
            - ./app/nginx.conf:/etc/nginx/templates/default.conf.template
        restart: unless-stopped
        depends_on:
            - backend
            - frontend
        env_file:
            - .env
