version: '3.4'

services:
    frontend:
        build: frontend
        user: ${DOCKER_USER}
        volumes:
            - ./frontend:/app:cached
        env_file:
            - .env

    backend:
        build: backend
        volumes:
            - ./backend:/app:cached
        working_dir: /app
        env_file:
            - .env

    nginx:
        image: nginx:1.19.3
        ports:
            - 80:80
        volumes:
            - ./app/nginx.conf:/etc/nginx/templates/default.conf.template
            - ./frontend/build:/usr/share/nginx/html/
        restart: always
        depends_on:
            - backend
            - frontend
        env_file:
            - .env
        labels:
            - "traefik.enable=true"
            - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_BASIC_AUTH}"
            - "traefik.http.routers.reader.rule=Host(`reader.dev.andyi95.com`)"
            - "traefik.http.routers.reader.middlewares=internal"
            - "traefik.http.services.reader.loadbalancer.server.port=8080"

