version: '3.4'

services:
    frontend:
        build: frontend
        user: ${DOCKER_USER}
        volumes:
            - ./frontend:/app:cached
        env_file:
            - .env

    backend:
        build: backend
        volumes:
            - ./backend:/app:cached
        working_dir: /app
        env_file:
            - .env

    nginx:
        image: nginx:1.19.3
        volumes:
            - ./app/nginx.conf:/etc/nginx/templates/default.conf.template
            - ./frontend/build:/usr/share/nginx/html/
        restart: unless-stopped
        depends_on:
            - backend
            - frontend
        env_file:
            - .env
