#!/bin/sh
set -e

echo "Deploying stage"
DEPLOY_COMPONENT=$1
echo $(whoami)
echo $(curl ifconfig.me)
echo $(pwd)
TAG=${CI_COMMIT_SHORT_SHA} docker compose pull $DEPLOY_COMPONENT
TAG=${CI_COMMIT_SHORT_SHA} docker compose up -d --force-recreate --remove-orphans --no-build $DEPLOY_COMPONENT
docker compose restart
