#!/bin/sh
set -e

echo "Deploying stage"
echo $(whoami)
echo $(curl ifconfig.me)
echo $(pwd)
TAG=${CI_COMMIT_SHORT_SHA} docker compose pull
TAG=${CI_COMMIT_SHORT_SHA} docker compose up -d --force-recreate --remove-orphans --no-build
docker compose restart
