#!/bin/sh

env -i \
CI_PROJECT_NAME=$CI_PROJECT_NAME \
sh -c '
  set -a;
  source .env.dist;

  export COMPOSE_FILE=docker-compose.yaml:docker-compose.stage.yaml
  export COMPOSE_PROJECT_NAME=reader-test
  export APP_VERSION=${APP_VERSION:-latest}
  export DEPLOYMENT_HOST=reader-test.home.andyi95.com
  (printenv | grep -v "^_=" | sort)
' > .env
cat .env

docker compose up -d
CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAdress}}{{end}}' ${COMPOSE_PROJECT_NAME}_nginx_1)
docker compose ps
sleep 10
if [ $(docker compose ps -q | wc -l) -ne $(docker compose config --services | wc -l) ]; then
    echo "Not all containers are running."
    docker compose ps
    exit 1
fi
HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" $CONTAINER_IP:80)
docker compose down
if [ -z "$HTTP_STATUS" ]; then
    echo "Failed to connect to $CONTAINER_IP:80"
    exit 1
fi

if [ $HTTP_STATUS -ne 200 ]; then
    echo "HTTP status code is not 200."
    exit 1
fi
