#!/bin/sh

docker-compose up -d
docker-compose ps
sleep 10
if [ $(docker-compose ps -q | wc -l) -ne $(docker-compose config --services | wc -l) ]; then
    echo "Not all containers are running."
    docker-compose ps
    exit 1
fi
docker-compose down
