name: Sync with Gitlab

on:
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync repo with Gitlab
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: action-pack/gitlab-sync@v3
        with:
          username: ${{ github.actor }}
          url: https://gitlab.andyi95.com/${{ github.repository }}.git
          token: ${{ secrets.GITLAB_TOKEN }}
